### ISSUE TITLE
Unable to mutate enum value through visitEnumValue

### ISSUE THREAD

**Issue by danielrearden** [yaacovCR/graphql-tools-fork#47]
Just hit this issue while trying to implement a simple directive that would let you change the value of an enum value:

```
export class ValueDirective extends SchemaDirectiveVisitor {
  visitEnumValue(
    enumValue: GraphQLEnumValue,
  ): GraphQLEnumValue {
  return {
    ...enumValue,
    value: this.args.string,
  }  
}
```

The intent here is to have an SDL-only way to deal with "internal" values of enum values without having to utilize the resolver map.

The issues is that `GraphQLEnumType` utilizes [several private properties](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L1241-L1243) that are derived from the initial set of values. I think the entire `GraphQLEnumType` would need to be recreated with an updated config whenever the visitor is called or after all directives are ran, but off-hand I'm not sure how feasible either approach is.

**Comment by yaacovCR** [comment]
Good catch, visitEnumValue has been broken since v14, see related issues fixed in https://github.com/apollographql/graphql-tools/pull/953 which did not include this fix.

Can you reopen this issue on upstream graphql-tools repository? Fork will soon be deprecated, see https://github.com/apollographql/graphql-tools/pull/1308

You can help out also by creating a PR with a failing test!

The fix will involve recreating the entire type with every changed value, as you suggest, see lines around https://github.com/apollographql/graphql-tools/blob/next/src/utils/visitSchema.ts#L200

Feel free to take a stab at it.

Not sure if your intent with this directive is best practice, as it does leak some private implementation details. But sure seems convenient.

**Comment by danielrearden** [comment]
Excellent! I'm elated to see all this work finally get merged upstream. I'll close this out and open a PR upstream with a failing test when I get a moment.
